version: '3'

volumes:
  pg_data:
  static:
  redis:
    driver: local
  celery:

services:

  postgres:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: aleksandrkomyagin/django_referal_system_backend:latest
    env_file: .env
    volumes:
      - static:/static
    depends_on:
      - postgres
    restart: always

  redis:
    image: redis
    command: redis-server
    expose:
      - '6379'
    ports:
     - 6379:6379
    volumes:
      - redis:/app/redis
    depends_on:
      - backend
    restart: always

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    command: python -m celery -A referal_system worker -l info -P eventlet
    volumes:
      - celery:/app/celery
    depends_on:
      - postgres
      - redis
    restart: always

  nginx:
    image: aleksandrkomyagin/django_referal_system_gateway:latest
    depends_on:
      - backend
    ports:
      - 8000:80
    volumes:
      - static:/static
    restart: always